Add temperature offsets
marian42/octoprint-preheat pull request #46
Opened 2021-02-12 10:02 UTC by Maroon-Cat

Possibility to set offsets for temperature gained from g-code file.

https://github.com/marian42/octoprint-preheat/issues/36

2021-02-15 21:03 UTC, marian42 commented
Thank you for the PR! After reading the issue #36, I understand the requested feature is to lower the temperature below that of the first layer. However, uses who aren't aware of this could be confused for two reasons:
- If I specify an offset of 5°, I'd expect the temperature to be 5° higher than it would otherwise be, and I'd expect it to be lower if I set it to a negative value.
- The headline in the settings says "Negative Temperature Offsets", but users can't input negative values

I think this could be made more clear by changing the feature to a regular offset that accepts positive and negative values. The settings page could contain a note that explains that negative values can be used to lower the temeperature.

Let me know what you think. Either way, I'm happy to merge this.

2021-02-16 15:15 UTC, Maroon-Cat commented
> Thank you for the PR! After reading the issue #36, I understand the requested feature is to lower the temperature below that of the first layer. However, uses who aren't aware of this could be confused for two reasons:
> 
>     * If I specify an offset of 5°, I'd expect the temperature to be 5° higher than it would otherwise be, and I'd expect it to be lower if I set it to a negative value.
> 
>     * The headline in the settings says "Negative Temperature Offsets", but users can't input negative values
> 
> 
> I think this could be made more clear by changing the feature to a regular offset that accepts positive and negative values. The settings page could contain a note that explains that negative values can be used to lower the temeperature.
> 
> Let me know what you think. Either way, I'm happy to merge this.

Dear Marian, thank you for you note.
That seems to be logical to correct the code for a more universal way. I can do that. 
However, a question of safety is arising. I prevented positive numbers to avoid overheating. I mean, If some one by chance enter 154° instead of 15°, he would probably damage his printer nozzle. Probably, I should set some possible maximal temperature, say 350, should I? It does not sound good, I think.
In the current state it is impossible situation, but in new way such a coincidence is possible.
By the way, could you please provide a use case for positive offset?

Probably, I should just add a minus before the field for temperature?

2021-02-17 05:40 UTC, Stady234 commented
> I prevented positive numbers to avoid overheating. I mean, If some one by chance enter 154° instead of 15°, he would probably damage his printer nozzle.

What about limiting the value of offset.. to say 30 degrees... if User has to enter a number higher(-/+) than that, they should re-slice with the proper parameters...

2021-02-20 20:10 UTC, marian42 commented
I think Octoprint already has a limit on temperatures. We could limit the (positive) offset.

An example usecase for positive offsets (although not a common one I admit) is that the printer does some calibration at the beginning of the print. While it does that, the temperature drops and once it's done calibrating, it will set its target temperature and wait until that is achieved. This could be sped up by setting a positive offset for the preheat temperature so that the printer will be closer to the correct starting temperature after cooling a bit during the calibration step.

2021-02-23 18:00 UTC, Maroon-Cat commented
Dear Marian,

I've changed the code for a positive temperature as well. It is limited by +50, and the plugin warns when temperature is too high. If you like, I can change something else.
P.S. Sorry for force-pushed commit. I am still relatively new and thereby made some errors while trying to update the previous commit.

2021-02-24 00:12 UTC, ubershy requested changes
Hello! Thanks for the patch.

It was me who created feature request for "negative offsets". Seems like people really want to have ability to set positive offsets. Well, I don't mind now. So be it. =)
In this patch I see that positive offset is allowed, but limited to 50 degrees. I think this limitation would not be effective as safety measure. So maybe we should just allow positive offsets without limitations?
What do you think about that, @marian42 and @Maroon-Cat?

I also marked some other minor problems in this patch. The typo should be fixed, I think.

2021-02-24 00:12 UTC, ubershy commented on octoprint_preheat/templates/preheat_settings.jinja2
> +			Temperature offsets are used either to lower preheat temperatures to prevent thermall degradation or to make any allownce. Does not affect fallback temperatures.
" or to make any allownce."
I don't understand what it means. Is there a typo?

2021-02-24 00:12 UTC, ubershy commented on octoprint_preheat/__init__.py
> +					"Offset results in very high temperature of {}°".format(initial))
If the temperature found in gcode file was already >= 260, even without offset, this warning may still be shown.

2021-02-24 00:12 UTC, ubershy commented on octoprint_preheat/__init__.py
> +			self._logger.info('Applied heating offset of {} for {}'.format(offset, tool))
Maybe we should not show this message in console if the offset is "0". Because nothing practically is applied in this case.

2021-02-24 17:18 UTC, Maroon-Cat commented on octoprint_preheat/templates/preheat_settings.jinja2
> +			Temperature offsets are used either to lower preheat temperatures to prevent thermall degradation or to make any allownce. Does not affect fallback temperatures.
As far as I understood 'to make allowance' means... Eeeehm yep, I've got a typo. Corrected.

2021-02-24 17:24 UTC, Maroon-Cat commented on octoprint_preheat/__init__.py
> +			self._logger.info('Applied heating offset of {} for {}'.format(offset, tool))
Corrected

2021-02-24 17:26 UTC, Maroon-Cat commented
I am not sure but still find preferable to have at least some a heating limitation. @marian42 , it is up to you to decide since you are the master.

2021-02-24 17:29 UTC, Maroon-Cat commented on octoprint_preheat/__init__.py
> +					"Offset results in very high temperature of {}°".format(initial))
Corrected

2021-03-16 19:35 UTC, marian42 commented
Sorry for not replying earlier. I'll merge this soon.

@Maroon-Cat It looks like you made changes in response to ubershy's comments, but you haven't pushed them yet.

2021-03-16 19:38 UTC, marian42 approved these changes

2021-03-16 19:38 UTC, merged